better error handling

diff --git a/trunk/doc/pkdocs b/trunk/doc/pkdocs
--- a/trunk/doc/pkdocs
+++ b/trunk/doc/pkdocs
@@ -17,26 +17,38 @@ PKDOCS_PWD=`pwd`
 
 echo "$ME Executing mkdocs..."
 echo
-$PKDOCS_PWD/mkdocs
+if $PKDOCS_PWD/mkdocs; then :
+else
+   echo "$ME Couldn't make the docs!"
+   echo "$ME Exiting..."
+   exit 1
 
 echo "$ME Packing html files..."
-
 cd $PKDOCS_PWD/$HTML_DIR
-
 rm -f $HTML_GZ
-tar -cf $HTML_TAR *.html *.php *.css fig/*
-gzip $HTML_TAR
-rm -f $HTML_TAR
+if tar -cf $HTML_TAR *.html *.php *.css fig/* && \
+   gzip $HTML_TAR && \
+   rm -f $HTML_TAR
+then :
+else
+   echo "$ME Couldn't zip the html files!"
+   echo "$ME Exiting..."
+   exit 1
+fi
 
 echo "$ME Packing t2t files..."
-
 cd $PKDOCS_PWD/$T2T_DIR
-
 rm -f $T2T_GZ
-tar -cf $T2T_TAR *.t2t *.html
-gzip $T2T_TAR
-rm -f $T2T_TAR
-mv $T2T_GZ $PKDOCS_PWD/$HTML_DIR
+if tar -cf $T2T_TAR *.t2t *.html && \
+   gzip $T2T_TAR && \
+   rm -f $T2T_TAR && \
+   mv $T2T_GZ $PKDOCS_PWD/$HTML_DIR
+then :
+else
+   echo "$ME Couldn't zip the t2t files!"
+   echo "$ME Exiting..."
+   exit 1
+fi  
 
 echo "$ME Docs packed!"
 echo
